table customer_tier
	lineageTag: 9a0e7779-db43-4cce-b85d-a6ab7eff9ef1

	column customer_number
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 29076871-9833-431f-9d55-22effb3405aa
		summarizeBy: none
		sourceColumn: customer_number

		annotation SummarizationSetBy = Automatic

	column Total_Spent
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3c9ea15e-e234-4251-9e32-23f985436a31
		summarizeBy: sum
		sourceColumn: Total_Spent

		annotation SummarizationSetBy = Automatic

	column customer_tier
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: e9ce01da-1ec4-47e9-9e8f-5623224d2f12
		summarizeBy: none
		sourceColumn: customer_tier
		sortByColumn: tier_rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column tier_rank
		dataType: int64
		formatString: 0
		lineageTag: c8bcdab6-f11d-44ad-b101-bb654ac359db
		summarizeBy: sum
		sourceColumn: tier_rank

		annotation SummarizationSetBy = Automatic

	partition customer_tier = m
		mode: import
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs("dbc-458a1273-b8ba.cloud.databricks.com", "/sql/1.0/warehouses/127ee04a7a01db03", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],
				    salesdb_Schema = workspace_Database{[Name="salesdb",Kind="Schema"]}[Data],
				    customer_tier_View = salesdb_Schema{[Name="customer_tier",Kind="View"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(customer_tier_View, "tier_rank", each if [customer_tier] = "VIP BRONZE" then 1 else if [customer_tier] = "VIP SILVER" then 2 else if [customer_tier] = "VIP GOLD" then 3 else if [customer_tier] = "VIP PLATINUM" then 4 else null),
				    #"Sorted Rows" = Table.Sort(#"Added Conditional Column",{{"tier_rank", Order.Ascending}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Sorted Rows",{{"tier_rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

